apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sherlock-redis
  namespace: sherlock
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sherlock-redis
    spec:
      containers:
      - image: redis:latest
        imagePullPolicy: Always
        name: sherlock-redis
        ports:
          - containerPort: 6379
            name: redis

---
apiVersion: v1
kind: Service
metadata:
  name: sherlock-redis
  namespace: sherlock
  labels:
    app: sherlock-redis
spec:
  selector:                
    app: sherlock-redis
  ports:
  - protocol: TCP
    name: redis   
    port: 6379          
    targetPort: 6379
  type: ClusterIP 

# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: sherlock-redis
#   namespace: sherlock
# spec:
#   serviceName: sherlock-redis
#   replicas: 1
#   selector:
#     matchLabels:
#       app: sherlock-redis
#   template:
#     metadata:
#       labels:
#         app: sherlock-redis
#     spec:
#       hostNetwork: true
#       hostname: sherlock-redis
#       containers:
#       - image: redis:latest
#         imagePullPolicy: Always
#         name: sherlock-redis
#         ports:
#           - containerPort: 6379

            