apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${namespace}-api
  namespace: ${namespace}
spec:
  replicas: ${api_replicas}
  template:
    metadata:
      labels:
        app: ${namespace}-api
    spec:
      containers:
      - image: kaihsianc/sherlock-api
        imagePullPolicy: Always
        name: ${namespace}-api
        env:
          - name: CELERY_BROKER_URL
            value: "redis://${namespace}-redis:6379"
          - name: CELERY_RESULT_BACKEND
            value: "redis://${namespace}-redis:6379"
        ports:
          - containerPort: 5000

    #  - image: python:3.6-alpine
    #     workingDir: /sherlock
    #     volumeMounts:
    #      - name: sherlock-api
    #        mountPath: /sherlock
    #        subPath: "Sherlock/sherlock-api"
    #     command: ["bash"]
    #     args: ["-c", "chmod u+rx setup.sh && sh setup.sh && gunicorn --bind 0.0.0.0:5000 --workers 3 app:app"]
    #   volumes:
    #   - name: sherlock-api
    #     gitRepo:
    #       repository: https://github.com/kaihsianc21/Sherlock.git
    #       revision: master
---
apiVersion: v1
kind: Service
metadata:
  name: ${namespace}-api
  namespace: ${namespace}
spec:
  type: LoadBalancer       
  ports:
  - port: ${api_port}             
    protocol: TCP          
    targetPort: 5000         
  selector:                
    app: ${namespace}-api

